### ISSUE TITLE
Dataset used

### ISSUE THREAD

**Issue by marianreuss** [faizankarim/table_detection_pdf#3]
Hi,

I'm currently working on table detection myself. Would you mind sharing which dataset you used for this project and how to get it?

Thanks!

**Comment by faizankarim** [comment]
I have created my own dataset. As it is an old project i am unable to find the dataset.

**Comment by marianreuss** [comment]
Thanks for the response. I actually ended up creating my own dataset as well :) 
There's also PubLayNet, I found, which mostly consists of data from scientific publications: https://github.com/ibm-aur-nlp/PubLayNet

Cheers

**Comment by faizankarim** [comment]
Great.

**Comment by LidorPrototype** [comment]
@mroyce1 
Can you share your implementation?

**Comment by faizankarim** [comment]
@LidorPrototype training code?

**Comment by LidorPrototype** [comment]
Yes looks like he/she was trying a machine / deep learning approach with it, and I want to see if its possible to use and learn from his approach with your code.
